In [183]:
import pandas as pd
import numpy as np

In [184]:
data_1 = pd.read_csv('Spaceship_Titanic.csv')
data_1

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [185]:
data_1['PassengerId'].apply(lambda i:i[-2:]).value_counts()

PassengerId
01    6217
02    1412
03     571
04     231
05     128
06      75
07      46
08      13
Name: count, dtype: int64

In [186]:
data_1=data_1.drop(['PassengerId'],axis=1)
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [187]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Cabin         8494 non-null   object
 3   Destination   8511 non-null   object
 4   Age           8514 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8512 non-null   float64
 7   FoodCourt     8510 non-null   float64
 8   ShoppingMall  8485 non-null   float64
 9   Spa           8510 non-null   float64
 10  VRDeck        8505 non-null   float64
 11  Name          8493 non-null   object
 12  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(6)
memory usage: 823.6+ KB

In [188]:
data_1.isna().sum()

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [189]:
data_1[data_1['HomePlanet'].isna()]

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
59,NaN,True,E/3/S,TRAPPIST-1e,33.0,False,0.0,0.0,NaN,0.0,0.0,Colatz Keen,True
113,NaN,False,A/0/P,TRAPPIST-1e,39.0,False,0.0,2344.0,0.0,65.0,6898.0,Batan Coning,False
186,NaN,True,D/6/P,55 Cancri e,24.0,False,0.0,0.0,NaN,0.0,0.0,Arraid Inicont,True
225,NaN,False,F/46/S,TRAPPIST-1e,18.0,False,313.0,1.0,691.0,283.0,0.0,Almone Sté,False
234,NaN,True,C/11/S,55 Cancri e,54.0,False,0.0,0.0,0.0,0.0,0.0,Diphah Amsive,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8515,NaN,False,E/582/P,TRAPPIST-1e,25.0,False,1258.0,0.0,22.0,19.0,0.0,Jurs Mone,False
8613,NaN,False,E/603/S,55 Cancri e,53.0,False,0.0,4017.0,0.0,13.0,3147.0,NaN,False
8666,NaN,False,F/1792/S,55 Cancri e,38.0,NaN,28.0,1208.0,973.0,207.0,0.0,Gian Perle,True
8674,NaN,False,F/1892/P,TRAPPIST-1e,13.0,False,39.0,0.0,1085.0,24.0,0.0,Ties Apple,False
8684,NaN,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True

In [190]:
x=data_1['HomePlanet'].value_counts().values
y=data_1['HomePlanet'].value_counts().index
print('x=',x) 
print('y=',y)

x= [4602 2131 1759]
y= Index(['Earth', 'Europa', 'Mars'], dtype='object', name='HomePlanet')

In [191]:
data_1['HomePlanet'].fillna(np.random.choice(y,p=x/np.sum(x)),inplace=True)

In [192]:
data_1.isna().sum()

HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [193]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [194]:
data_1[data_1['CryoSleep'].isna()]

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
92,Earth,NaN,G/12/P,TRAPPIST-1e,2.0,False,0.0,0.0,0.0,0.0,0.0,Thewis Connelson,True
98,Earth,NaN,F/21/P,TRAPPIST-1e,27.0,False,0.0,0.0,570.0,2.0,131.0,Carry Cleachrand,False
104,Europa,NaN,B/5/P,TRAPPIST-1e,40.0,False,0.0,331.0,0.0,0.0,1687.0,Aldeba Bootious,False
111,Mars,NaN,F/24/P,TRAPPIST-1e,26.0,False,0.0,0.0,0.0,0.0,NaN,Rohs Pead,True
152,Earth,NaN,E/11/S,TRAPPIST-1e,58.0,False,0.0,985.0,0.0,5.0,0.0,Hilip Grifford,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8620,Europa,NaN,C/308/P,55 Cancri e,44.0,False,0.0,0.0,0.0,0.0,0.0,Bellus Platch,True
8651,Earth,NaN,G/1498/P,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,Hard Hinglendez,False
8664,Earth,NaN,G/1490/S,TRAPPIST-1e,32.0,False,0.0,0.0,0.0,0.0,0.0,NaN,True
8675,Earth,NaN,F/1893/P,TRAPPIST-1e,44.0,False,1030.0,1015.0,0.0,11.0,NaN,Annah Gilleyons,True
8687,Europa,NaN,A/97/P,TRAPPIST-1e,30.0,False,0.0,3208.0,0.0,2.0,330.0,Atlasym Conable,True

In [195]:
data_1['CryoSleep'].isna().sum()

217

In [196]:
for i,lm in enumerate(data_1['CryoSleep']):
   if type(lm) is float:
       if (data_1['RoomService'][i]+data_1['FoodCourt'][i]+data_1['ShoppingMall'][i]+ data_1['Spa'][i]+data_1['VRDeck'][i])==0:
           data_1['CryoSleep'].iloc[i]=True
       else:
           data_1['CryoSleep'].iloc[i]=False

C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=True
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['CryoSleep'].iloc[i]=False
C:\Users\Admin\AppData\Local\Temp\ipykernel_7900\2407131317.py:4: SettingWithCopyWarning:

In [197]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [198]:
data_1['Cabin']=data_1['Cabin'].apply(lambda i:i.split('/')[-1] if isinstance(i,str) else np.nan)

In [199]:
cab=data_1['Cabin'].value_counts()
cab

Cabin
S    4288
P    4206
Name: count, dtype: int64

In [200]:
ind =cab.index
v = cab.values
print('ind=',ind)
print('values=',v)

ind= Index(['S', 'P'], dtype='object', name='Cabin')
values= [4288 4206]

In [201]:
data_1['Cabin'].fillna(np.random.choice(ind,p=v/np.sum(v)),inplace=True)

In [202]:
data_1.isna().sum()

HomePlanet        0
CryoSleep         0
Cabin             0
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [203]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [204]:
d = data_1['Destination'].value_counts()
d

Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64

In [205]:
ind =d.index
v = d.values
print('ind=',ind)
print('values=',v)

ind= Index(['TRAPPIST-1e', '55 Cancri e', 'PSO J318.5-22'], dtype='object', name='Destination')
values= [5915 1800  796]

In [206]:
data_1['Destination'].fillna(np.random.choice(ind,p=v/np.sum(v)),inplace=True)

In [207]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [208]:
data_1['Age'].describe()

count    8514.000000
mean       28.827930
std        14.489021
min         0.000000
25%        19.000000
50%        27.000000
75%        38.000000
max        79.000000
Name: Age, dtype: float64

In [212]:
data_1['Age'].fillna(data_1['Age'].mean(),inplace=True)

In [213]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [214]:
data_1['VIP'].value_counts()

VIP
False    8291
True      199
Name: count, dtype: int64

In [216]:
data_1['VIP'].fillna(False,inplace=True)

In [217]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,Europa,False,P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,Earth,False,S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,Europa,False,S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,Europa,False,S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,Earth,False,S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,Earth,True,S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,Earth,False,S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,Europa,False,S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,Europa,False,S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [220]:
data_1['RoomService'].fillna(0,inplace=True)
data_1['FoodCourt'].fillna(0,inplace=True)
data_1['ShoppingMall'].fillna(0,inplace=True)
data_1['Spa'].fillna(0,inplace=True)
data_1['VRDeck'].fillna(0,inplace=True)

In [221]:
data_1['Sells']=data_1['RoomService']+data_1['FoodCourt']+data_1['ShoppingMall']+ data_1['Spa']+data_1['VRDeck']

In [222]:
data_1['Sells'].isna().sum()

0

In [224]:
data_1.drop(['RoomService','FoodCourt','ShoppingMall','Spa','VRDeck'],axis=1,inplace=True)

In [225]:
data_1

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,Name,Transported,Sells
0,Europa,False,P,TRAPPIST-1e,39.0,False,Maham Ofracculy,False,0.0
1,Earth,False,S,TRAPPIST-1e,24.0,False,Juanna Vines,True,736.0
2,Europa,False,S,TRAPPIST-1e,58.0,True,Altark Susent,False,10383.0
3,Europa,False,S,TRAPPIST-1e,33.0,False,Solam Susent,False,5176.0
4,Earth,False,S,TRAPPIST-1e,16.0,False,Willy Santantines,True,1091.0
...,...,...,...,...,...,...,...,...,...
8688,Europa,False,P,55 Cancri e,41.0,True,Gravior Noxnuther,False,8536.0
8689,Earth,True,S,PSO J318.5-22,18.0,False,Kurta Mondalley,False,0.0
8690,Earth,False,S,TRAPPIST-1e,26.0,False,Fayey Connon,True,1873.0
8691,Europa,False,S,55 Cancri e,32.0,False,Celeon Hontichre,False,4637.0
8692,Europa,False,S,TRAPPIST-1e,44.0,False,Propsh Hontichre,True,4826.0

In [226]:
data_1.drop(['Name'],axis=1,inplace=True)

In [227]:
data_1.isna().sum()

HomePlanet     0
CryoSleep      0
Cabin          0
Destination    0
Age            0
VIP            0
Transported    0
Sells          0
dtype: int64

In [229]:
data_1.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HomePlanet   8693 non-null   object
 1   CryoSleep    8693 non-null   object
 2   Cabin        8693 non-null   object
 3   Destination  8693 non-null   object
 4   Age          8693 non-null   float64
 5   VIP          8693 non-null   bool
 6   Transported  8693 non-null   bool
 7   Sells        8693 non-null   float64
dtypes: bool(2), float64(2), object(4)
memory usage: 2.0 MB

In [230]:
data_1['Earth']=(data_1['HomePlanet']=='Earth').astype('int8')

In [231]:
data_1['Mars']=(data_1['HomePlanet']=='Mars').astype('int8')

In [232]:
data_1.drop(['HomePlanet'],axis=1,inplace=True)

In [233]:
data_1

,CryoSleep,Cabin,Destination,Age,VIP,Transported,Sells,Earth,Mars
0,False,P,TRAPPIST-1e,39.0,False,False,0.0,0,0
1,False,S,TRAPPIST-1e,24.0,False,True,736.0,1,0
2,False,S,TRAPPIST-1e,58.0,True,False,10383.0,0,0
3,False,S,TRAPPIST-1e,33.0,False,False,5176.0,0,0
4,False,S,TRAPPIST-1e,16.0,False,True,1091.0,1,0
...,...,...,...,...,...,...,...,...,...
8688,False,P,55 Cancri e,41.0,True,False,8536.0,0,0
8689,True,S,PSO J318.5-22,18.0,False,False,0.0,1,0
8690,False,S,TRAPPIST-1e,26.0,False,True,1873.0,1,0
8691,False,S,55 Cancri e,32.0,False,False,4637.0,0,0
8692,False,S,TRAPPIST-1e,44.0,False,True,4826.0,0,0

In [235]:
data_1['CryoSleep']=data_1['CryoSleep'].astype('int8')

In [236]:
data_1

,CryoSleep,Cabin,Destination,Age,VIP,Transported,Sells,Earth,Mars
0,0,P,TRAPPIST-1e,39.0,False,False,0.0,0,0
1,0,S,TRAPPIST-1e,24.0,False,True,736.0,1,0
2,0,S,TRAPPIST-1e,58.0,True,False,10383.0,0,0
3,0,S,TRAPPIST-1e,33.0,False,False,5176.0,0,0
4,0,S,TRAPPIST-1e,16.0,False,True,1091.0,1,0
...,...,...,...,...,...,...,...,...,...
8688,0,P,55 Cancri e,41.0,True,False,8536.0,0,0
8689,1,S,PSO J318.5-22,18.0,False,False,0.0,1,0
8690,0,S,TRAPPIST-1e,26.0,False,True,1873.0,1,0
8691,0,S,55 Cancri e,32.0,False,False,4637.0,0,0
8692,0,S,TRAPPIST-1e,44.0,False,True,4826.0,0,0

In [237]:
data_1['Cabin']=(data_1['Cabin']=='P').astype('int8')

In [238]:
data_1['Dest_1']=(data_1['Destination']=='TRAPPIST-1e').astype('int8')

In [239]:
data_1['Dest_2']=(data_1['Destination']=='55 Cancri e').astype('int8')

In [240]:
data_1.drop('Destination',axis=1,inplace=True)

In [241]:
data_1

,CryoSleep,Cabin,Age,VIP,Transported,Sells,Earth,Mars,Dest_1,Dest_2
0,0,1,39.0,False,False,0.0,0,0,1,0
1,0,0,24.0,False,True,736.0,1,0,1,0
2,0,0,58.0,True,False,10383.0,0,0,1,0
3,0,0,33.0,False,False,5176.0,0,0,1,0
4,0,0,16.0,False,True,1091.0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
8688,0,1,41.0,True,False,8536.0,0,0,0,1
8689,1,0,18.0,False,False,0.0,1,0,0,0
8690,0,0,26.0,False,True,1873.0,1,0,1,0
8691,0,0,32.0,False,False,4637.0,0,0,0,1
8692,0,0,44.0,False,True,4826.0,0,0,1,0

In [242]:
data_1['Age']=data_1['Age'].astype('int8')

In [243]:
data_1['VIP']=data_1['VIP'].astype('int8')

In [244]:
data_1

,CryoSleep,Cabin,Age,VIP,Transported,Sells,Earth,Mars,Dest_1,Dest_2
0,0,1,39,0,False,0.0,0,0,1,0
1,0,0,24,0,True,736.0,1,0,1,0
2,0,0,58,1,False,10383.0,0,0,1,0
3,0,0,33,0,False,5176.0,0,0,1,0
4,0,0,16,0,True,1091.0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
8688,0,1,41,1,False,8536.0,0,0,0,1
8689,1,0,18,0,False,0.0,1,0,0,0
8690,0,0,26,0,True,1873.0,1,0,1,0
8691,0,0,32,0,False,4637.0,0,0,0,1
8692,0,0,44,0,True,4826.0,0,0,1,0

In [245]:
data_1['Transported']=data_1['Transported'].astype('int8')

In [246]:
data_1

,CryoSleep,Cabin,Age,VIP,Transported,Sells,Earth,Mars,Dest_1,Dest_2
0,0,1,39,0,0,0.0,0,0,1,0
1,0,0,24,0,1,736.0,1,0,1,0
2,0,0,58,1,0,10383.0,0,0,1,0
3,0,0,33,0,0,5176.0,0,0,1,0
4,0,0,16,0,1,1091.0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
8688,0,1,41,1,0,8536.0,0,0,0,1
8689,1,0,18,0,0,0.0,1,0,0,0
8690,0,0,26,0,1,1873.0,1,0,1,0
8691,0,0,32,0,0,4637.0,0,0,0,1
8692,0,0,44,0,1,4826.0,0,0,1,0

In [247]:
data_1['Sells'].describe()

count     8693.000000
mean      1440.866329
std       2803.045694
min          0.000000
25%          0.000000
50%        716.000000
75%       1441.000000
max      35987.000000
Name: Sells, dtype: float64

In [248]:
data_1['Sells']=data_1['Sells']/data_1['Sells'].max()

In [249]:
data_1

,CryoSleep,Cabin,Age,VIP,Transported,Sells,Earth,Mars,Dest_1,Dest_2
0,0,1,39,0,0,0.000000,0,0,1,0
1,0,0,24,0,1,0.020452,1,0,1,0
2,0,0,58,1,0,0.288521,0,0,1,0
3,0,0,33,0,0,0.143830,0,0,1,0
4,0,0,16,0,1,0.030317,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
8688,0,1,41,1,0,0.237197,0,0,0,1
8689,1,0,18,0,0,0.000000,1,0,0,0
8690,0,0,26,0,1,0.052047,1,0,1,0
8691,0,0,32,0,0,0.128852,0,0,0,1
8692,0,0,44,0,1,0.134104,0,0,1,0

In [251]:
data_1.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CryoSleep    8693 non-null   int8
 1   Cabin        8693 non-null   int8
 2   Age          8693 non-null   int8
 3   VIP          8693 non-null   int8
 4   Transported  8693 non-null   int8
 5   Sells        8693 non-null   float64
 6   Earth        8693 non-null   int8
 7   Mars         8693 non-null   int8
 8   Dest_1       8693 non-null   int8
 9   Dest_2       8693 non-null   int8
dtypes: float64(1), int8(9)
memory usage: 144.4 KB

In [252]:
data_1['Age']=data_1['Age']/data_1['Age'].max()

In [253]:
data_1

,CryoSleep,Cabin,Age,VIP,Transported,Sells,Earth,Mars,Dest_1,Dest_2
0,0,1,0.493671,0,0,0.000000,0,0,1,0
1,0,0,0.303797,0,1,0.020452,1,0,1,0
2,0,0,0.734177,1,0,0.288521,0,0,1,0
3,0,0,0.417722,0,0,0.143830,0,0,1,0
4,0,0,0.202532,0,1,0.030317,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
8688,0,1,0.518987,1,0,0.237197,0,0,0,1
8689,1,0,0.227848,0,0,0.000000,1,0,0,0
8690,0,0,0.329114,0,1,0.052047,1,0,1,0
8691,0,0,0.405063,0,0,0.128852,0,0,0,1
8692,0,0,0.556962,0,1,0.134104,0,0,1,0

In [254]:
data_1.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CryoSleep    8693 non-null   int8
 1   Cabin        8693 non-null   int8
 2   Age          8693 non-null   float64
 3   VIP          8693 non-null   int8
 4   Transported  8693 non-null   int8
 5   Sells        8693 non-null   float64
 6   Earth        8693 non-null   int8
 7   Mars         8693 non-null   int8
 8   Dest_1       8693 non-null   int8
 9   Dest_2       8693 non-null   int8
dtypes: float64(2), int8(8)
memory usage: 203.9 KB

In [255]:
y = data_1['Transported']
x = data_1.drop('Transported', axis=1)

In [256]:
y.value_counts()

Transported
1    4378
0    4315
Name: count, dtype: int64

# Homework

1.Train_test_split

2.Model_Fit_Predict(KNN,Naive_Bayes,Random_Forest,Gradient_Boosting)

3.Ընտրել լավագույն հիպեր–պարամետրեր(Grid Search)

4.Metrics(Ստանալ արդյունքները և համեմատել)(Accurancy_score)